export const SLICE_CHARACTER = ':'

export const AXIS_INNER_KEEP_CHARACTER = '^'
export const AXIS_INNER_CHARACTER = '-'
export const AXIS_RESULT_CHARACTER = '*'

export const RESULT = 'result'
export const INNER = 'of'
export const WITH = 'with'
export const OF = 'of'

export const MAX = 'max'
export const MIN = 'min'
export const ADD = 'add'
export const MEAN = 'mean'
export const NORM = 'norm'
export const ROUND = 'round'
export const ASSIGN = 'assign'
export const DIVIDE = 'divide'
export const DEFAULT = 'default'
export const SUBTRACT = 'subtract'
export const MULTIPLY = 'multiply'
export const IDENTITY = 'identity'

export const SHAPE = 'shape'
export const OFFSET = 'offset'
export const CONTIG = 'contig'
export const STRIDES = 'strides'
